Traceback (most recent call last):
  File "/mnt/c/Users/fonse/Documents/improving-LOR/algorithms/simulated_annealing.py", line 10, in <module>
    from fitness import Fitness
ModuleNotFoundError: No module named 'fitness'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 38, in <module>
    from .request import RequestMethods
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 3, in <module>
    from .filepost import encode_multipart_formdata
  File "/usr/lib/python3/dist-packages/urllib3/filepost.py", line 10, in <module>
    from .fields import RequestField
  File "/usr/lib/python3/dist-packages/urllib3/fields.py", line 3, in <module>
    import mimetypes
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1469, in find_spec
  File "<frozen importlib._bootstrap_external>", line 101, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 93, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 87, in _path_stat
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/mnt/c/Users/fonse/Documents/improving-LOR/algorithms/simulated_annealing.py", line 10, in <module>
    from fitness import Fitness
ModuleNotFoundError: No module named 'fitness'
